const menuData = [
  {
    id: "item-1",
    name: "Cinnamoroll",
    ingredients: ["Flour", "Cinnamon", "Sugar", "Butter"],
    price: "$4.50",
    location: "Bakery House",
    image: "/images/cinnamorol.jpeg",
    category: "veg",
  },
  {
    id: "item-2",
    name: "Corndog",
    ingredients: ["Sausage", "Cornmeal Batter", "Oil"],
    price: "$3.99",
    location: "Street Eats",
    image: "/images/corndog.jpeg",
    category: "non-veg",
  },
  {
    id: "item-3",
    name: "CreamCheesePasta",
    ingredients: ["Pasta", "Cream", "Cheese", "Garlic"],
    price: "$7.99",
    location: "Pasta Point",
    image: "/images/CreamCheesePasta.jpeg",
    category: "veg",
  },
  {
    id: "item-4",
    name: "Fries",
    ingredients: ["Potatoes", "Salt", "Oil"],
    price: "$2.99",
    location: "Snack Corner",
    image: "/images/fries.jpeg",
    category: "veg",
  },
  {
    id: "item-5",
    name: "FriedChicken",
    ingredients: ["Chicken", "Spices", "Flour", "Oil"],
    price: "$6.99",
    location: "Chicken Shack",
    image: "/images/FriedChicken.jpeg",
    category: "non-veg",
  },
  {
    id: "item-6",
    name: "Margherita",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    price: "$8.99",
    location: "Pizza Place",
    image: "/images/MargheritaPizza.jpeg",
    category: "veg",
  },
  {
    id: "item-7",
    name: "Momo",
    ingredients: ["Flour", "Meat or Vegetables", "Spices"],
    price: "$5.50",
    location: "Nepali Kitchen",
    image: "/images/momo.jpeg",
    category: "non-veg",
  },
  {
    id: "item-8",
    name: "Panipuri",
    ingredients: ["Semolina Balls", "Spiced Water", "Potato", "Chickpeas"],
    price: "$2.50",
    location: "Chaat Center",
    image: "/images/panipuri.jpeg",
    category: "veg",
  },
  {
    id: "item-9",
    name: "Salmon",
    ingredients: ["Rice", "Salmon", "Seaweed", "Soy Sauce"],
    price: "$9.99",
    location: "Sushi Bar",
    image: "/images/salmonsushi.jpeg",
    category: "non-veg",
  },
  {
    id: "item-10",
    name: "Sausage",
    ingredients: ["Pork", "Spices", "Salt"],
    price: "$4.25",
    location: "Meat Deli",
    image: "/images/sausage.jpeg",
    category: "non-veg",
  },
  {
    id: "item-11",
    name: "Sushi",
    ingredients: ["Rice", "Fish", "Seaweed"],
    price: "$8.50",
    location: "Sushi World",
    image: "/images/sushi.jpeg",
    category: "non-veg",
  },
  {
    id: "item-12",
    name: "Tornado",
    ingredients: ["Potatoes", "Salt", "Cheese (optional)", "Spices"],
    price: "$3.75",
    location: "Fair Stand",
    image: "/images/tornadoFries.jpeg",
    category: "veg",
  },
];

export default menuData;
