const menuData = [
  {
    name: "Veggie Pizza",
    ingredients: ["Cheese", "Tomato", "Capsicum"],
    price: "$9.99",
    location: "Pizza Place",
    image: "/images/pizza.jpeg",
    category: "veg",
  },
  {
    name: "Chicken Burger",
    ingredients: ["Bun", "Chicken", "Lettuce"],
    price: "$7.99",
    location: "Burger Joint",
    image: "/images/cinnamorol.jpeg",
    category: "non-veg",
  },
  {
    name: "Lemon Soda",
    ingredients: ["Lemon", "Soda", "Sugar"],
    price: "$2.99",
    location: "Cool Drinks",
    image: "/images/FriedChicken.jpeg",
    category: "drinks",
  },
  {
    name: "Chicken Burger",
    ingredients: ["Bun", "Chicken", "Lettuce"],
    price: "$7.99",
    location: "Burger Joint",
    image: "/images/cinnamorol.jpeg",
    category: "non-veg",
  },
  {
    name: "Lemon Soda",
    ingredients: ["Lemon", "Soda", "Sugar"],
    price: "$2.99",
    location: "Cool Drinks",
    image: "/images/FriedChicken.jpeg",
    category: "drinks",
  },
  {
    name: "Chicken Burger",
    ingredients: ["Bun", "Chicken", "Lettuce"],
    price: "$7.99",
    location: "Burger Joint",
    image: "/images/cinnamorol.jpeg",
    category: "non-veg",
  },
  {
    name: "Lemon Soda",
    ingredients: ["Lemon", "Soda", "Sugar"],
    price: "$2.99",
    location: "Cool Drinks",
    image: "/images/FriedChicken.jpeg",
    category: "drinks",
  },
  {
    name: "Chicken Burger",
    ingredients: ["Bun", "Chicken", "Lettuce"],
    price: "$7.99",
    location: "Burger Joint",
    image: "/images/cinnamorol.jpeg",
    category: "non-veg",
  },
  {
    name: "Lemon Soda",
    ingredients: ["Lemon", "Soda", "Sugar"],
    price: "$2.99",
    location: "Cool Drinks",
    image: "/images/FriedChicken.jpeg",
    category: "drinks",
  },
  {
    name: "Chicken Burger",
    ingredients: ["Bun", "Chicken", "Lettuce"],
    price: "$7.99",
    location: "Burger Joint",
    image: "/images/cinnamorol.jpeg",
    category: "non-veg",
  },
  {
    name: "Lemon Soda",
    ingredients: ["Lemon", "Soda", "Sugar"],
    price: "$2.99",
    location: "Cool Drinks",
    image: "/images/FriedChicken.jpeg",
    category: "drinks",
  },
];

export default menuData;
